#!/usr/bin/env node
// Single writer for program/tracker.json. Never hand-edit that file.
//
//   node program/tracker.mjs ready              # tasks whose deps are met
//   node program/tracker.mjs iterate            # bump the iteration counter
//   node program/tracker.mjs set <id> --status done --evidence file:path
//   node program/tracker.mjs set <id> --status failed --error "why"
//   node program/tracker.mjs render             # regenerate TRACKER.md
//   node program/tracker.mjs report             # final report to stdout
//
// Readiness: (pending|failed) && retries < max_retries
//            && iteration >= retry_after_iteration && every dep done.
// `set --status failed` flips to dead_letter at the retry ceiling — callers
// never make that decision themselves.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const TRACKER = path.join(HERE, "tracker.json");
const RENDERED = path.join(HERE, "TRACKER.md");

const TERMINAL = new Set(["done", "dead_letter", "needs_human"]);
const STATUSES = new Set(["pending", "in_progress", "failed", ...TERMINAL]);

const read = () => JSON.parse(readFileSync(TRACKER, "utf8"));
const write = (db) => writeFileSync(TRACKER, JSON.stringify(db, null, 2) + "\n");
const byId = (db, id) => db.tasks.find((t) => t.id === id);

/** A task is selectable when nothing upstream is outstanding and its backoff has expired. */
export function isReady(db, t) {
  if (!["pending", "failed"].includes(t.status)) return false;
  if (t.retries >= t.max_retries) return false;
  if (db.iteration < t.retry_after_iteration) return false;
  return t.deps.every((d) => byId(db, d)?.status === "done");
}

/** Pending work behind a dep that can never finish is stuck, not waiting. */
export function isBlocked(db, t) {
  if (TERMINAL.has(t.status)) return false;
  return t.deps.some((d) => {
    const dep = byId(db, d);
    return !dep || dep.status === "dead_letter" || dep.status === "needs_human";
  });
}

function cmdReady(db) {
  const ready = db.tasks.filter((t) => isReady(db, t));
  if (!ready.length) { console.log("(nothing ready)"); return; }
  for (const t of ready) {
    console.log(`${t.id}\t${t.type}\t${t.milestone}\t${t.title}`);
    console.log(`\tfiles: ${t.files.join(", ") || "(none)"}`);
  }
}

function cmdIterate(db) {
  db.iteration += 1;
  write(db);
  console.log(`iteration -> ${db.iteration}`);
}

function cmdSet(db, id, args) {
  const t = byId(db, id);
  if (!t) { console.error(`unknown task: ${id}`); process.exit(1); }

  const status = args.status;
  if (!status || !STATUSES.has(status)) {
    console.error(`--status must be one of: ${[...STATUSES].join(", ")}`);
    process.exit(1);
  }

  if (status === "failed") {
    t.retries += 1;
    t.last_error = args.error ?? "(no detail)";
    // Exponential backoff, then dead-letter at the ceiling. Never loop forever.
    t.retry_after_iteration = db.iteration + 2 ** t.retries;
    t.status = t.retries >= t.max_retries ? "dead_letter" : "failed";
  } else {
    t.status = status;
    if (status === "done") {
      if (args.evidence) t.evidence.push(args.evidence);
      if (!t.evidence.length) {
        console.error(`${id}: refusing to mark done with no evidence`);
        process.exit(1);
      }
      t.last_error = null;
    }
    if (args.error) t.last_error = args.error;
  }

  t.status_iteration = db.iteration;
  if (args.commit) t.commit = args.commit;
  write(db);
  console.log(`${id} -> ${t.status}${t.status === "dead_letter" ? " (retry ceiling)" : ""}`);
}

const COUNT_ORDER = ["done", "in_progress", "pending", "failed", "needs_human", "dead_letter"];

function tally(db) {
  const c = Object.fromEntries(COUNT_ORDER.map((s) => [s, 0]));
  for (const t of db.tasks) c[t.status] = (c[t.status] ?? 0) + 1;
  return c;
}

function cmdRender(db) {
  const c = tally(db);
  const pct = Math.round((100 * c.done) / db.tasks.length);
  const milestones = [...new Set(db.tasks.map((t) => t.milestone))].sort();

  const mark = (t) =>
    ({ done: "x", in_progress: "~", dead_letter: "!", needs_human: "?" }[t.status] ?? " ");

  const lines = [
    "# Tirtha Atlas — program tracker",
    "",
    "> GENERATED by `program/tracker.mjs render`. Never hand-edit.",
    "",
    `**Iteration ${db.iteration}** · ${c.done}/${db.tasks.length} done (${pct}%)`,
    "",
    `| ${COUNT_ORDER.join(" | ")} |`,
    `|${COUNT_ORDER.map(() => "---").join("|")}|`,
    `| ${COUNT_ORDER.map((s) => c[s]).join(" | ")} |`,
    "",
  ];

  for (const m of milestones) {
    const tasks = db.tasks.filter((t) => t.milestone === m);
    const label = db.milestone_titles?.[m] ?? m;
    const pr = db.milestone_prs?.[m];
    lines.push(`## ${m} — ${label}${pr ? ` (PR #${pr})` : ""}`, "");
    for (const t of tasks) {
      const blocked = isBlocked(db, t) ? " **[blocked]**" : "";
      lines.push(`- [${mark(t)}] \`${t.id}\` ${t.title}${blocked}`);
      if (t.last_error) lines.push(`      - last error: ${t.last_error}`);
      if (t.evidence.length) lines.push(`      - evidence: ${t.evidence.join(", ")}`);
    }
    lines.push("");
  }

  const stuck = db.tasks.filter((t) => t.status === "dead_letter" || t.status === "needs_human");
  if (stuck.length) {
    lines.push("## Needs human", "");
    for (const t of stuck) lines.push(`- \`${t.id}\` ${t.title} — ${t.last_error ?? t.status}`);
    lines.push("");
  }

  writeFileSync(RENDERED, lines.join("\n"));
  console.log(`rendered ${RENDERED} (${c.done}/${db.tasks.length} done)`);
}

function cmdReport(db) {
  const c = tally(db);
  console.log(`iteration ${db.iteration} · ${c.done}/${db.tasks.length} done`);
  for (const s of COUNT_ORDER) if (c[s]) console.log(`  ${s}: ${c[s]}`);
  const open = db.tasks.filter((t) => !TERMINAL.has(t.status));
  console.log(open.length ? `\nopen: ${open.map((t) => t.id).join(", ")}` : "\nall tasks terminal");
}

function parseArgs(argv) {
  const out = {};
  for (let i = 0; i < argv.length; i += 2) {
    if (!argv[i]?.startsWith("--")) continue;
    out[argv[i].slice(2)] = argv[i + 1];
  }
  return out;
}

const [cmd, ...rest] = process.argv.slice(2);
const db = read();

switch (cmd) {
  case "ready": cmdReady(db); break;
  case "iterate": cmdIterate(db); break;
  case "set": cmdSet(db, rest[0], parseArgs(rest.slice(1))); break;
  case "render": cmdRender(db); break;
  case "report": cmdReport(db); break;
  default:
    console.error("usage: tracker.mjs ready|iterate|set <id> --status <s>|render|report");
    process.exit(1);
}
